name: Vaultwarden Build (Linux-musl)

on:
  workflow_dispatch:
    inputs:
      tag_choice:
        description: "版本选择"
        required: true
        default: "release"
        type: choice
        options:
          - release
          - latest
          - custom
      tag:
        description: "自定义 commit"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 安装 Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools pkg-config libssl-dev sqlite3 libsqlite3-dev jq curl git tar

      - name: 添加 musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: vaultwarden 版本选择
        id: get_tag
        shell: bash
        run: |
          if [ "${{ github.event.inputs.tag_choice }}" = "release" ]; then
            release=$(curl -s https://api.github.com/repos/dani-garcia/vaultwarden/releases/latest)
            tag=$(echo "$release" | jq -r .tag_name)
            echo "tag=$tag" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.tag_choice }}" = "latest" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.tag_choice }}" = "custom" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: 设置版本号兜底
        id: set_version
        shell: bash
        run: |
          if [ -z "${{ steps.get_tag.outputs.tag }}" ]; then
            echo "version=latest" >> $GITHUB_OUTPUT
          else
            echo "version=${{ steps.get_tag.outputs.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: 克隆 vaultwarden 仓库
        run: git clone https://github.com/dani-garcia/vaultwarden

      - name: 切换版本
        if: ${{ steps.get_tag.outputs.tag != '' }}
        run: git checkout ${{ steps.get_tag.outputs.tag }}
        working-directory: vaultwarden

      - name: 下载并解压 web-vault
        run: |
          release=$(curl -s https://api.github.com/repos/dani-garcia/bw_web_builds/releases/latest)
          asset_url=$(echo "$release" | jq -r '.assets[] | select(.name | test("web.*\\.tar\\.gz$")) | .browser_download_url' | head -n1)
          file_name=$(basename "$asset_url")

          curl -L "$asset_url" -o "$file_name"
          tar -xzf "$file_name" -C vaultwarden
          dir=$(find vaultwarden -maxdepth 1 -type d -name "bw_web*")
          if [ -n "$dir" ]; then
            mv "$dir" vaultwarden/web-vault
          fi

      - name: 编译 vaultwarden (musl 静态)
        run: cargo build --release --target x86_64-unknown-linux-musl
        working-directory: vaultwarden

      - name: 重命名文件带版本号
        run: mv ./vaultwarden/target/x86_64-unknown-linux-musl/release/vaultwarden ./vaultwarden_${{ steps.set_version.outputs.version }}

      - name: 调整 web-vault 目录
        run: mv vaultwarden/web-vault ./web-vault

      - name: 打包文件
        uses: actions/upload-artifact@v4
        with:
          name: Vaultwarden_${{ steps.set_version.outputs.version }}_Linux-musl
          path: |
            vaultwarden_${{ steps.set_version.outputs.version }}
            web-vault
