name: Vaultwarden Build

on:
  workflow_dispatch:
    inputs:
      tag_choice:
        description: "版本选择"
        required: true
        default: "release"
        type: choice
        options:
          - release
          - latest
          - custom
      tag:
        description: "自定义 commit"
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 安装 Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: 检查工具版本
        run: git version && cargo --version

      - name: vaultwarden 版本选择
        id: get_tag
        shell: pwsh
        run: |
          if ("${{ github.event.inputs.tag_choice }}" -eq "release") {
            $release = Invoke-RestMethod -Uri "https://api.github.com/repos/dani-garcia/vaultwarden/releases/latest"
            echo "Using release tag: $($release.tag_name)"
            echo "tag=$($release.tag_name)" >> $env:GITHUB_OUTPUT
          } elseif ("${{ github.event.inputs.tag_choice }}" -eq "latest") {
            echo "Using latest commit"
            echo "tag=" >> $env:GITHUB_OUTPUT
          } elseif ("${{ github.event.inputs.tag_choice }}" -eq "custom") {
            echo "Using custom tag: ${{ github.event.inputs.tag }}"
            echo "tag=${{ github.event.inputs.tag }}" >> $env:GITHUB_OUTPUT
          }

      - name: 克隆 vaultwarden 仓库
        run: git clone https://github.com/dani-garcia/vaultwarden

      - name: 切换版本
        if: ${{ steps.get_tag.outputs.tag != '' }}
        run: git checkout ${{ steps.get_tag.outputs.tag }}
        working-directory: vaultwarden

      - name: 下载 web-vault
        shell: pwsh
        run: |
          $Release = Invoke-RestMethod -Uri "https://api.github.com/repos/dani-garcia/bw_web_builds/releases/latest"
          $Asset = $Release.assets | Where-Object { $_.name -like "*.zip" }
          $DownloadUrl = $Asset.browser_download_url
          $FileName = $Asset.name
          Invoke-WebRequest -Uri $DownloadUrl -OutFile $FileName
          Expand-Archive -Path $FileName -DestinationPath web-vault

      - name: 安装 vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: 使用 vcpkg 安装依赖
        run: |
          .\vcpkg\vcpkg.exe integrate install
          .\vcpkg\vcpkg.exe install openssl:x64-windows-static

      - name: 编译 vaultwarden
        run: cargo build --features sqlite --release
        working-directory: vaultwarden
        env:
          RUSTFLAGS: "-Ctarget-feature=+crt-static"

      - name: 重命名文件带版本号
        run: move .\vaultwarden\target\release\vaultwarden.exe .\vaultwarden_${{ steps.get_tag.outputs.tag }}.exe

      - name: 打包文件
        uses: actions/upload-artifact@v4
        with:
          name: Vaultwarden_${{ steps.get_tag.outputs.tag }}
          path: |
            vaultwarden_${{ steps.get_tag.outputs.tag }}.exe
            web-vault
